config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "posts#index"
  resources :users

  get 'manage', to: 'users#manage'
  get 'createuser', to: 'users#createuser'

  resources :users, only: [:manage] do
    member do
      patch :ban
    end
  end

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # include Visible

  belongs_to :user
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  # validates :body, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable

  class User < ActiveRecord::Base
    after_create :assign_default_role

    def assign_default_role
      self.add_role(:newuser) if self.roles.blank?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
  #
  protected
  #
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts=Post.all
    @newpost=Post.new
    @users = User.all
  end

  def show
    @post=Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    # @post = Post.new(post_params)
    # @post.user = current_user
    # @post = Post.create(post_params.merge(user_id: current_user.id))
    @post = Post.create(post_params.merge(user_id: current_user.id))
    if @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity

    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!

    redirect_to root_path, status: :see_other
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :user_id , :status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def manage
  @users = User.all
end

def ban
  @user = User.find(params[:id])
  if @user.access_locked?
    @user.unlock_access!
  else
    @user.lock_access!
  end
  redirect_to users_path, notice: "User access locked: #{@user.access_locked?}"
end

def createuser
  @user = User.all
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def ban_status(user)
    if user.access_locked?
      'Activate'
    else
      'Deactivate'
    end
  end
end

app/views/comments/_comment.html.erb
<div style="display: flex">
  <%= image_tag("mazeimage.png") %>
  <p class="thirdConatinerShowCommentName"><%= @post.user.first_name %> <%=@post.user.last_name %></p>
</div>
<p style="margin-left: 45px"><%= comment.body %></p>
<hr color="lightgrey">

app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build] do |form| %>
<!--  <p>-->
<!--    <%#= form.label :commenter %><br>-->
    <%#= form.text_field :commenter %>
<!--  </p>-->

  <p>
<!--    <%#= form.label :body %><br>-->
  <div class="thirdConatinerCreateComment"><%= form.text_field :body, placeholder:"Write a comment.." %></div>
  </p>

  <p>
    <button type="submit" class="thirdConatinerCreateCommentButton">
      <%#= form.submit%>
      <%= image_tag "commentbutton.png", class:"thirdContainerCreateCommentIcon" %></button>

  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MazeRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form|%>

  <div class="secondContainerCreatePostBar">
    <%= form.text_area :body, placeholder: "whats happening ?"%><br>
  </div>

  <div class="privatePublicDropButton">
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private'], selected: 'public' %>
  </div>

  <div class="secondConatinerCreateArticleButton">
    <%= form.submit %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1> Edit Article</h1>

<%= render "form",post: @post %>

app/views/posts/index.html.erb
<div class="navbarTopMazeProject">
    <div class="mazeImgNavbar">
      <%= image_tag "mazeimage.png" %>
    </div>
    <div class="mazeTextNavbar">
      <h1>Maze</h1>
    </div>
    <input type="text" id="searchPostNavbar" placeholder="Search for something here... ">
</div>

<div class="sidebar">
  <a class="feedImageButtonSideNavbar"> <%=image_tag("feedImage2.png", style: "margin-right:22px")%> Feed</a>
  <a> <%=image_tag("profileImage.png", style: "margin-right:22px") %>  Profile</a>
  <a href="/manage", class="ReportsSideBar1"><%=image_tag("manageUser.png", style: "margin-right:22px") %>Manage User</a>
  <a><%=image_tag("logoutImage.png", style: "margin-right:22px") %><%= link_to "Logout",destroy_user_session_path, data: { "turbo-method": :delete } , class: "logOutButtonMazeSideNavbar" %></a>
  <%#= button_to "Logout", destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } } %>

</div>

<div>
  <% if current_user.has_role? :admin %>
    <div class="mazeProjectRightSidebar">

      <div class="mazeProjectRightSidebarTopNavbar">
        <%= image_tag("userImageEllipse1.png") %>
        <h4 style="margin-left: 80px; position: absolute;top: -14px">Vishal Agarwal</h4>
      </div>

      <h4 style="margin-left: 8px;">Users List</h4>



      <% @users.each do |user| %>
        <div class="mazeProjectRightSidebarUsersList">
          <%= image_tag("MazeImageCircle.png") %>
          <p class="mazeProjectRightSidebarUsersListname"><%= user.first_name %></p>
          <p class="mazeProjectRightSidebarUsersListname"><%= user.last_name %></p>
        </div>
      <% end %>

    </div>
  <% end %>
</div>



<div class="secondContainerMazeProject">
  <br>
  <div class="createPostContainer">
    <%= render "form", post: @newpost %>

    <div class="secondConatinerPhotoVideoPic">
      <div class="secondConatinerVideoPic">
      <div><%= image_tag "video.png" %></div>
      <div>Live Video</div>
    </div>
      <div class = "secondConatinerPhotoPic">
      <div><%= image_tag "Video.png" %></div>
      <div>Photo/Video</div>
    </div>
      <div class = "secondConatinerFeelingPic">
      <div><%= image_tag "felling.png" %></div>
      <div>Feeling</div>
    </div>
    </div>
  </div>
  <br>
  <% if current_user.has_role? :admin %>
    <% @posts.reverse.each do |post| %>

      <div class="thirdContainerPostBody">

        <div class="thirdContainerTitleBar">
          <%= image_tag "mazeimage.png" %>
          <div class="thirdConatinerUserNameTimeStamp">
            <div class="thirdContainerUserName"><%=  post.user.first_name %> <%= post.user.last_name %><br></div>
            <div class="thirdContainerTimeStamp"><%= time_ago_in_words(post.created_at)%>, public</div>
          </div>
        </div>

        <div class="dropdown" >
          <span class="dropbtn">...</span>
          <div class="dropdown-content">
            <%= link_to "Edit", edit_post_path(post) %>
            <%= link_to "Destroy", post_path(post), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            } %>
          </div>
        </div>

        <div class="thirdContainerBodyOfPost"><%= link_to post.body, post %>
          <br>
          <br>
          <hr>
          <br>
          <div class="thirdContainerLikeCommentPics">
            <div class="thirdContainerLikePic">
              <div><%= image_tag "heart.png" %></div>
              <div>  Like</div>
            </div>

            <div class="thirdContainerCommentPic">
              <div><%= image_tag "comment.png" %></div>
              <div><%= link_to "comment", post %></div>
            </div>
          </div>
          <br>
          <hr>
        </div>

        <% @post = post %>
        <%= render 'comments/form'%>
        <br>

        <div class="thirdConatinerShowComment">
          <div style="display: flex">
            <%= image_tag("mazeimage.png") %>
            <p class="thirdConatinerShowCommentName"><%= @post.user.first_name %> <%=@post.user.last_name %></p>
          </div>

          <p style="margin-left: 45px"><%= post.comments.order('created_at DESC').first&.body %></p>
        </div>
        <%#= render post.comments %>

      </div>
    <% end %>



  <% else %>

    <% @posts.reverse.each do |post| %>
      <% if post.status == "public" %>
        <div class="thirdContainerPostBody">

          <div class="thirdContainerTitleBar">
            <%= image_tag "mazeimage.png" %>
            <div class="thirdConatinerUserNameTimeStamp">
              <div class="thirdContainerUserName"><%=  post.user.first_name %> <%= post.user.last_name %><br></div>
              <div class="thirdContainerTimeStamp"><%= time_ago_in_words(post.created_at)%>, public</div>
            </div>
          </div>

          <div class="dropdown" >
            <span class="dropbtn">...</span>
            <div class="dropdown-content">
              <%= link_to "Edit", edit_post_path(post) %>
              <%= link_to "Destroy", post_path(post), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
            </div>
          </div>

          <div class="thirdContainerBodyOfPost"><%= link_to post.body, post %>
            <br>
            <br>
            <hr>
            <br>
            <div class="thirdContainerLikeCommentPics">
              <div class="thirdContainerLikePic">
                <div><%= image_tag "heart.png" %></div>
                <div>  Like</div>
              </div>

              <div class="thirdContainerCommentPic">
                <div><%= image_tag "comment.png" %></div>
                <div><%= link_to "comment", post %></div>
              </div>
            </div>
            <br>
            <hr>
          </div>

          <% @post = post %>
          <%= render 'comments/form'%>
          <br>

          <div class="thirdConatinerShowComment">
            <div style="display: flex">
              <%= image_tag("mazeimage.png") %>
              <p class="thirdConatinerShowCommentName"><%= @post.user.first_name %> <%=@post.user.last_name %></p>
            </div>

            <p style="margin-left: 45px"><%= post.comments.order('created_at DESC').first&.body %></p>
          </div>

        </div>
      <% end %>
      <br>
    <% end %>
  <% end %>
</div>










<% if user_signed_in? %>
  Are you admin? <%= current_user.has_role? :admin %>
<% end %>

app/views/posts/show.html.erb
<div>
  <nav class="navbarTopMazeProjectShowPage">
    <div class="mazeImgNavbarShowPage">
      <%= image_tag "mazeimage.png" %>
    </div>
    <div class="mazeTextNavbarShowPage">
      <h1>Maze</h1>
    </div>
    <input type="text" id="searchPostNavbarShowPage" placeholder="Search for something here... ">
  </nav>
</div>

<div class="sidebar">
  <a><%=image_tag("feedImage2.png", style: "margin-right:22px")%><%= link_to "Feed", root_path(@post) , class: "FeedButtonMazeSideNavbarShowPage" %> </a>
  <div class="mazeProjectLeftSidebarprofilelogoutImageConatiner">
    <a><%=image_tag("profileImage.png", style: "margin-right:22px") %>  Profile</a>
    <a><%=image_tag("logoutImage.png", style: "margin-right:22px") %><%= link_to "Logout",destroy_user_session_path, data: { "turbo-method": :delete } , class: "logOutButtonMazeSideNavbarShowPage" %></a>
  </div>
</div>

<div class="secondContainerMazeProjectShowPage">
  <br>
  <div class="thirdContainerPostBodyShowPage">
    <div class="thirdContainerTitleBarShowPage">
      <%= image_tag "mazeimage.png" %>
      <div class="thirdConatinerUserNameTimeStampShowPage">
        <div class="thirdContainerUserNameShowPage"><%=  @post.user.first_name %> <%= @post.user.last_name %><br></div>
        <div class="thirdContainerTimeStampShowPage"><%= time_ago_in_words(@post.created_at)%>, public</div>
      </div>
      <div class="dropShowdown" >
        <span class="dropShowbtn">...</span>
        <div class="dropShowdown-content">
          <%= link_to "Edit", edit_post_path(@post) %>
          <%= link_to "Destroy", post_path(@post), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %>
        </div>
      </div>
      <p><%= @post.body %></p>

      <br>
      <hr color="lightgrey">
      <br>
      <div class="thirdContainerLikeCommentPicsShowPage">
        <div class="thirdContainerLikePicShowPage">
          <div><%= image_tag "heart.png" %></div>
          <div>Like</div>
        </div>
        <div class="thirdContainerCommentPicShowPage">
          <div><%= image_tag "comment.png" %></div>
          <div>comment</div>

        </div>
        <br>
      </div>
      <br>
      <hr color="lightgrey">
      <br>

      <%= render 'comments/form' %>

      <h2 style="color: rgba(96, 97, 101, 0.6);">Comments</h2>
      <hr color="lightgrey">
      <%= render @post.comments %>

    </div>

  </div>
</div>

app/views/users/createuser.html.erb
<div class="navbarTopMazeProject">
  <div class="mazeImgNavbar">
    <%= image_tag "mazeimage.png" %>
  </div>
  <div class="mazeTextNavbar">
    <h1>Maze</h1>
  </div>
  <h1 class="manageUserManagement">User Management</h1>
</div>

<div class="sidebar">
  <a><%=image_tag("feedImage2.png", style: "margin-right:22px")%><%= link_to "Feed", root_path(@post) , class: "manageFeedButtonMazeSideNavbarShowPage" %> </a>

  <div class="managemazeProjectLeftSidebarprofilelogoutImageConatiner">
    <a> <%=image_tag("profileImage.png", style: "margin-right:22px") %>  Profile</a>
    <a  class="feedImageButtonSideNavbar"><%=image_tag("manageUser.png", style: "margin-right:22px") %>Manage User</a>
    <a><%=image_tag("logoutImage.png", style: "margin-right:22px") %><%= link_to "Logout",destroy_user_session_path, data: { "turbo-method": :delete } , class: "logOutButtonMazeSideNavbar" %></a>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } } %>
  </div>

</div>

<div class="managemazeProjectRightSidebar">

  <div class="managemazeProjectRightSidebarTopNavbar">
    <%= image_tag("userImageEllipse1.png") %>
    <h2 style="margin-left: 80px; position: absolute;top: -14px">Vishal Agarwal</h2>
  </div>
</div>

<div class="createSecondContainerMazeProject">
  <h1>Add Users</h1>
  <textarea class="createNameMobileEmail">Add name</textarea><br>
  <textarea class="createNameMobileEmail">Mobile No.</textarea><br>
  <textarea class="createNameMobileEmail">Email</textarea>

  <%= button_to 'create user',createuser_path, method: :get, class: "managecreateUserButton"%>



</div>

app/views/users/manage.html.erb
<div class="navbarTopMazeProject">
  <div class="mazeImgNavbar">
    <%= image_tag "mazeimage.png" %>
  </div>
  <div class="mazeTextNavbar">
    <h1>Maze</h1>
  </div>
  <h1 class="manageUserManagement">User Management</h1>
</div>

<div class="sidebar">
  <a><%=image_tag("feedImage2.png", style: "margin-right:22px")%><%= link_to "Feed", root_path(@post) , class: "manageFeedButtonMazeSideNavbarShowPage" %> </a>

  <div class="managemazeProjectLeftSidebarprofilelogoutImageConatiner">
    <a> <%=image_tag("profileImage.png", style: "margin-right:22px") %>  Profile</a>
    <a  class="feedImageButtonSideNavbar"><%=image_tag("manageUser.png", style: "margin-right:22px") %>Manage User</a>
    <a><%=image_tag("logoutImage.png", style: "margin-right:22px") %><%= link_to "Logout",destroy_user_session_path, data: { "turbo-method": :delete } , class: "logOutButtonMazeSideNavbar" %></a>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } } %>
  </div>

</div>

<div class="managemazeProjectRightSidebar">

  <div class="managemazeProjectRightSidebarTopNavbar">
    <%= image_tag("userImageEllipse1.png") %>
    <h2 style="margin-left: 80px; position: absolute;top: -14px">Vishal Agarwal</h2>
  </div>
</div>

<div class="manageSecondContainerMazeProject">
  <p class="manageListOfUsersText">List Of Users</p>
  <%= button_to 'create user',createuser_path, method: :get, class: "managecreateUserButton"%>

  <%@users.each do |user| %>
    <br>
    <div class="manageUsersActivateDeactivate">

      <%= image_tag("mazeimage.png") %>
      <div class="managegreenDotImage"><%=image_tag("greendot.png") %></div>

      <p class="manageUserName"><%= user.first_name %> <%= user.last_name %></p>

      <p class="manageUserNumber"><%= user.phone_number %>  </p>
      <p class="manageUserEmail">  <%= user.email %></p>

      <%#= user.access_locked? %>
      <%#= button_to 'ban' ,ban_user_path(user) , method: :patch  %>
      <%= button_to ban_status(user), ban_user_path(user), method: :patch, class: "manageUsersActivateDeactivateButton" %>

    </div>
<br>
  <% end %>

</div>

app/views/users/postfour.csv.erb
<% headers = ['First Name','Last Name','post Count','Comment Count'] %>
<%= CSV.generate_line headers %>
<% @user.each do |user| %>

  <% Post.all.where(user_id: user.id).each do |post| %>
  <% if Post.all.where(user_id: user.id).count > 2 %>
  <%= CSV.generate_line([user.first_name, user.last_name, Post.all.where(user_id: user.id).count, Comment.all.where(user_id: user.id, post_id: post.id).count]) %>
  <% else %>
  <%= CSV.generate_line(['nil','nil','nil','nil']) %>
<% end %>
<% end %>
<% end %>

app/views/users/postwise.csv.erb
<% headers = ['body','comments'] %>
<%= CSV.generate_line headers %>
<% @post.each do | post| %>
  <% post.comments.each do |comment| %>
    <%= CSV.generate_line([post.body, comment.body]) %>
  <% end %>
<% end %>

app/views/users/reports.csv.erb
<% headers = ['First Name','Last Name','post Count','Comment Count'] %>
<%= CSV.generate_line headers %>
<% @user.each do |user| %>

  <% Post.all.where(user_id: user.id).each do |post| %>
  <%= CSV.generate_line([user.first_name, user.last_name, Post.all.where(user_id: user.id).count, Comment.all.where(user_id: user.id, post_id: post.id).count]) %>
  <% end %>

<% end %>

app/views/users/reports.html.erb
<div class="navbarTopMazeProject">
  <div class="mazeImgNavbar">
    <%= image_tag "mazeimage.png" %>
  </div>
  <div class="mazeTextNavbar">
    <h1>Maze</h1>
  </div>
  <h1 class="manageUserManagement">User Management</h1>
</div>

<div class="sidebar">
<<<<<<< HEAD
  <a><%= image_tag("feedImage2.png", style: "margin-right:22px") %><%= link_to "Feed", root_path(@post), class: "manageFeedButtonMazeSideNavbarShowPage" %> </a>

  <div class="managemazeProjectLeftSidebarprofilelogoutImageConatiner">
    <a> <%= image_tag("profileImage.png", style: "margin-right:22px") %>  Profile</a>
    <a><%= image_tag("manageUser.png", style: "margin-right:22px") %>Manage User</a>
    <a class="feedImageButtonSideNavbar"><%= image_tag("reportsimage.png", style: "margin-right:22px; background-color:grey") %>
      Reports</a>
    <a><%= image_tag("logoutImage.png", style: "margin-right:22px") %><%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, class: "logOutButtonMazeSideNavbar" %></a>
    <%#= button_to "Logout", destroy_user_session_path, method: :delete, form: { data: { turbo: :false } } %>
=======
  <a><%=image_tag("feedImage2.png", style: "margin-right:22px")%><%= link_to "Feed", root_path(@post) , class: "manageFeedButtonMazeSideNavbarShowPage" %> </a>

  <div class="managemazeProjectLeftSidebarprofilelogoutImageConatiner">
    <a> <%=image_tag("profileImage.png", style: "margin-right:22px") %>  Profile</a>
    <a  ><%=image_tag("manageUser.png", style: "margin-right:22px") %>Manage User</a>
    <a class="feedImageButtonSideNavbar"><%= image_tag("reportsimage.png", style: "margin-right:22px; background-color:grey") %>Reports</a>
    <a><%=image_tag("logoutImage.png", style: "margin-right:22px") %><%= link_to "Logout",destroy_user_session_path, data: { "turbo-method": :delete } , class: "logOutButtonMazeSideNavbar" %></a>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } } %>
>>>>>>> origin/vishalweek3
  </div>

</div>

<div class="managemazeProjectRightSidebar">

  <div class="managemazeProjectRightSidebarTopNavbar">
    <%= image_tag("userImageEllipse1.png") %>
    <h2 style="margin-left: 80px; position: absolute;top: -14px">Vishal Agarwal</h2>
  </div>
</div>

<<<<<<< HEAD
<div class="reportManageSecondContainerMazeProject">
  <div class="reportAllUsersW4">

    <div class="reportAllUsersBlueCircle"><%= image_tag("bluecircle.png") %></div>
    <div class="reportAllUsersCont"><%= image_tag("week4image.png") %></div>
    <h2 class="reportAllUsersText">All Users</h2>
    <h6 class="reportPostCommentsText">Posts,comments count</h6>
    <%#= button_to 'Download',reports_path(format: :csv) %>
    <div class="reportAllUsersDownloadBUtton"><%= link_to 'Download CSV', reports_path(format: :csv) %></div>
    <div class="reportAllUsersDownloadBUttonXL"><%=  link_to 'Download Excel', resultxl_path(format: :xlsx)%></div>
  </div>
  <div class="reportAllUsersW4">

    <div class="reportAllUsersBlueCircle"><%= image_tag("bluecircle.png") %></div>
    <div class="reportAllUsersCont"><%= image_tag("week4image.png") %></div>
    <h2 class="reportAllUsersText">All Users</h2>
    <h6 class="reportPostCommentsText">having more than 10 posts.users</h6>
    <div class="reportAllUsersDownloadBUtton"><%= link_to 'Download CSV', postfour_path(format: :csv) %></div>
    <div class="reportAllUsersDownloadBUttonXL"><%= link_to 'download Excel', posttwoxl_path(format: :xlsx) %></div>
  </div>

  <div class="reportAllUsersW4">

    <div class="reportAllUsersBlueCircle"><%= image_tag("bluecircle.png") %></div>
    <div class="reportAllUsersCont"><%= image_tag("week4image.png") %></div>
    <h2 class="reportAllUsersText">All Users</h2>
    <h6 class="reportPostCommentsText">Description, Comments</h6>

    <div class="reportAllUsersDownloadBUtton"><%= link_to 'Download CSV', postwise_path(format: :csv) %></div>
    <div class="reportAllUsersDownloadBUttonXL"><%= link_to 'Download Excel', reportbodyxl_path(format: :xlsx) %></div>
  </div>
</div>











































  <%# form_for(@post) do |f| %>
    <%#= f.radio_button :contactmethod, 'email', :checked => true %>
    <%#= label :contactmethod_email, 'Email' %>

  <%# end %>


  <!--    <div class="form-group">-->
  <!--      <%#= f.label :gender %> <br />-->
  <%#= f.label :gender_male, 'male' %>
  <%#= f.radio_button :gender, 'male', :checked => true %>
  <%#= f.label :gender_female, 'female' %>
  <!--      <%#= f.radio_button :gender, 'female' %><br />-->
  <!--    </div>-->


  <%# radio_button :gender %>
=======
<div class="manageSecondContainerMazeProject">
  <h1>hello</h1>

  <%#= link_to 'export users', reports_path(format: :csv) %>

</div>
>>>>>>> origin/vishalweek3